<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputPath>../../Build/</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
		<PackageReference Include="Serilog" Version="4.4.0" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="System.Buffers" />
		<Using Include="System.Buffers.Binary" />
		<Using Include="System.Collections.Concurrent" />
		<Using Include="System.Diagnostics" />
		<Using Include="System.Net" />
		<Using Include="System.Net.Sockets" />
		<Using Include="System.Runtime.CompilerServices" />
		<Using Include="System.Security.Cryptography" />
		<Using Include="System.Text" />
		<Using Include="System.Threading.Channels" />
		<Using Include="Myethos.Network.Codec" />
		<Using Include="Myethos.Network.Security" />
		<Using Include="Org.BouncyCastle.Crypto.Engines" />
		<Using Include="Org.BouncyCastle.Crypto.Parameters" />
		<Using Include="Org.BouncyCastle.Math" />
	</ItemGroup>

</Project>